'''
Certain post-processing will want individual text files, rather than one giant csv of data.
(e.g. you want to run MALLET on all the fics)
In that case, run this script on the csv generated by ao3_get_fanfics.  
It will create a folder named after the csv_name, and populate it with individual text files
that each contain the body of one story. The text files will be named 'work_id.txt', so you can 
cross-reference back to the csv for metadata. 
'''

import csv
import os

def main():
	csv.field_size_limit(1000000000)  # up the field size because stories are long
	path = os.getcwd()
	csv_names = [f for f in os.listdir(path) if '-fic.csv' in f]
	csv_names = [f for f in csv_names if 'error' not in f]
	print csv_names
	
	# clean extension
<<<<<<< HEAD
=======
	if ".csv" not in csv_name:
		csv_name = csv_name + ".csv"
>>>>>>> 225c0f95c9d2b5158a05225ec79e1fbc43c74791


	for csv_name in csv_names:
		if ".csv" in csv_name:
			csv_name_short = csv_name[:-4]
		with open(csv_name, 'rb') as csvfile:
			folder_name = csv_name_short + "_text_files"
			if not os.path.exists(folder_name):
				os.makedirs(folder_name)
			rd = csv.reader(csvfile, delimiter=',', quotechar='"')
			next(rd)  # skip the header row
			for row in rd:
				with open(folder_name + "/" + row[0] + ".txt", "w") as text_file:
					text_file.write(row[-1])

		#also, just write its stats in the new stats folder 		
		with open(csv_name, 'rb') as csvfile, open("newstats/" + csv_name_short + '-stats.csv', 'wb') as stats_file:
			rd = csv.reader(csvfile, delimiter=',', quotechar='"')
			writer = csv.writer(stats_file, delimiter = ';')
			for row in rd:
				writer.writerow(row[:-1])

		print 'done with ', csv_name

main()