'''
Certain post-processing will want individual text files, rather than one giant csv of data.
(e.g. you want to run MALLET on all the fics)
In that case, run this script on the csv generated by ao3_get_fanfics.  
It will create a folder named after the csv_name, and populate it with individual text files
that each contain the body of one story. The text files will be named 'work_id.txt', so you can 
cross-reference back to the csv for metadata. 
'''

import csv
import os

def main():
	csv.field_size_limit(1000000000)  # up the field size because stories are long
	csv_name = raw_input("What is the csv called?  ")
	
	# clean extension
	if ".csv" not in csv_name:
		csv_name = csv_name + ".csv"

	with open(csv_name, 'rb') as csvfile:
		folder_name = csv_name + "_text_files"
		if not os.path.exists(folder_name):
			os.makedirs(folder_name)
		rd = csv.reader(csvfile, delimiter=',', quotechar='"')
		next(rd)  # skip the header row
		for row in rd:
			work_id = row[0]
			with open(folder_name + "/" + row[0] + ".txt", "w") as text_file:
				text_file.write(row[-1])

main()